[program:watson]
command=%(venv)s/bin/python -m uvicorn api:app --host 0.0.0.0 --port 9000
directory=%(project_dir)s
user=%(user)s
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=30
redirect_stderr=true
stdout_logfile=%(project_dir)s/logs/supervisor.log
environment=PYTHONUNBUFFERED="1"

; Para usar o executavel PyInstaller, comente a linha 'command' acima e descomente:
; command=%(project_dir)s/dist/watson/watson

[group:watson]
programs=watson
